version: '3.4'

services: 
  ks:
    container_name: ks
    image: ${DOCKER_REGISTRY-}ks
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    volumes:    
      - ./src:/app/src
      - ./dist:/app/dist